version: '3'

services:

    frontend:
      build:
        context: .
        dockerfile: Dockerfile
      command: npm run dev
      volumes:
        - ./hrpanorama-task/:/usr/src/app
      ports:
        - "8090:9000"
